import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | WhereToFIRE',
  description: 'Terms of Service for WhereToFIRE.com',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-slate-900">
      <div className="max-w-3xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-8">Terms of Service</h1>
        
        <div className="prose dark:prose-invert max-w-none space-y-6 text-gray-700 dark:text-gray-300">
          <p className="text-sm text-gray-500 dark:text-gray-400">Last updated: February 2026</p>
          
          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using WhereToFIRE.com ("the Site"), you accept and agree to be bound by these Terms of Service. 
              If you do not agree to these terms, please do not use the Site.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">2. Educational Purpose Only</h2>
            <p>
              The Site provides financial calculators and information for <strong>educational and informational purposes only</strong>. 
              The Site does not provide financial, tax, legal, immigration, or investment advice.
            </p>
            <p>
              All calculations, projections, and estimates are hypothetical and based on assumptions that may not reflect 
              your actual situation. Results should not be relied upon for making financial decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">3. No Professional Advice</h2>
            <p>
              Nothing on this Site constitutes professional financial, tax, legal, or immigration advice. The information provided:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Is general in nature and may not apply to your specific circumstances</li>
              <li>May be outdated, incomplete, or inaccurate</li>
              <li>Should not replace consultation with qualified professionals</li>
              <li>Does not create any professional-client relationship</li>
            </ul>
            <p className="mt-4">
              <strong>Always consult with qualified financial advisors, tax professionals, and immigration lawyers 
              before making any decisions based on information from this Site.</strong>
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">4. Accuracy of Information</h2>
            <p>
              While we strive to provide accurate information, we make no guarantees regarding:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Tax rates, brackets, or regulations (which change frequently)</li>
              <li>Cost of living indices and comparisons</li>
              <li>Currency exchange rates</li>
              <li>Visa and immigration requirements</li>
              <li>Pension and social security information</li>
              <li>Healthcare costs and availability</li>
              <li>Any calculations or projections generated by the Site</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">5. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, WHERETOFIRE.COM AND ITS OWNERS, OPERATORS, AND AFFILIATES 
              SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES 
              ARISING FROM YOUR USE OF THE SITE OR RELIANCE ON ANY INFORMATION PROVIDED.
            </p>
            <p>
              This includes, but is not limited to, damages arising from:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Financial losses from investment or relocation decisions</li>
              <li>Tax penalties or unexpected tax obligations</li>
              <li>Immigration issues or visa denials</li>
              <li>Errors or inaccuracies in calculations</li>
              <li>Changes in laws, regulations, or market conditions</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">6. No Warranty</h2>
            <p>
              THE SITE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY WARRANTIES OF ANY KIND, 
              EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, 
              FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">7. User Responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Use the Site only for lawful purposes</li>
              <li>Verify all information independently before making decisions</li>
              <li>Consult qualified professionals for personalized advice</li>
              <li>Not rely solely on the Site for financial planning</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">8. Intellectual Property</h2>
            <p>
              All content on this Site, including text, graphics, logos, and software, is the property of 
              WhereToFIRE.com or its content suppliers and is protected by intellectual property laws.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">9. Third-Party Links</h2>
            <p>
              The Site may contain links to third-party websites. We are not responsible for the content, 
              accuracy, or practices of any third-party sites.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">10. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Continued use of the Site after 
              changes constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of Ireland, 
              without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">12. Contact</h2>
            <p>
              For questions about these Terms, please contact us through the Site.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-200 dark:border-slate-700">
          <a href="/" className="text-blue-600 dark:text-blue-400 hover:underline">← Back to Calculator</a>
        </div>
      </div>
    </div>
  );
}
